// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 15.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'wombie';

  static const String assets_chars_zombie = 'assets/chars/zombie';
  static const String wombie$assets_chars_zombie = 'packages/wombie/assets/chars/zombie';

  static const String assets_chars_zombie_poses_zombie_action1_png = 'assets/chars/zombie/poses/zombie_action1.png';
  static const String wombie$assets_chars_zombie_poses_zombie_action1_png = 'packages/wombie/assets/chars/zombie/poses/zombie_action1.png';

  static const String assets_chars_zombie_poses_zombie_action2_png = 'assets/chars/zombie/poses/zombie_action2.png';
  static const String wombie$assets_chars_zombie_poses_zombie_action2_png = 'packages/wombie/assets/chars/zombie/poses/zombie_action2.png';

  static const String assets_chars_zombie_poses_zombie_back_png = 'assets/chars/zombie/poses/zombie_back.png';
  static const String wombie$assets_chars_zombie_poses_zombie_back_png = 'packages/wombie/assets/chars/zombie/poses/zombie_back.png';

  static const String assets_chars_zombie_poses_zombie_cheer1_png = 'assets/chars/zombie/poses/zombie_cheer1.png';
  static const String wombie$assets_chars_zombie_poses_zombie_cheer1_png = 'packages/wombie/assets/chars/zombie/poses/zombie_cheer1.png';

  static const String assets_chars_zombie_poses_zombie_cheer2_png = 'assets/chars/zombie/poses/zombie_cheer2.png';
  static const String wombie$assets_chars_zombie_poses_zombie_cheer2_png = 'packages/wombie/assets/chars/zombie/poses/zombie_cheer2.png';

  static const String assets_chars_zombie_poses_zombie_climb1_png = 'assets/chars/zombie/poses/zombie_climb1.png';
  static const String wombie$assets_chars_zombie_poses_zombie_climb1_png = 'packages/wombie/assets/chars/zombie/poses/zombie_climb1.png';

  static const String assets_chars_zombie_poses_zombie_climb2_png = 'assets/chars/zombie/poses/zombie_climb2.png';
  static const String wombie$assets_chars_zombie_poses_zombie_climb2_png = 'packages/wombie/assets/chars/zombie/poses/zombie_climb2.png';

  static const String assets_chars_zombie_poses_zombie_duck_png = 'assets/chars/zombie/poses/zombie_duck.png';
  static const String wombie$assets_chars_zombie_poses_zombie_duck_png = 'packages/wombie/assets/chars/zombie/poses/zombie_duck.png';

  static const String assets_chars_zombie_poses_zombie_fall_png = 'assets/chars/zombie/poses/zombie_fall.png';
  static const String wombie$assets_chars_zombie_poses_zombie_fall_png = 'packages/wombie/assets/chars/zombie/poses/zombie_fall.png';

  static const String assets_chars_zombie_poses_zombie_hang_png = 'assets/chars/zombie/poses/zombie_hang.png';
  static const String wombie$assets_chars_zombie_poses_zombie_hang_png = 'packages/wombie/assets/chars/zombie/poses/zombie_hang.png';

  static const String assets_chars_zombie_poses_zombie_hold1_png = 'assets/chars/zombie/poses/zombie_hold1.png';
  static const String wombie$assets_chars_zombie_poses_zombie_hold1_png = 'packages/wombie/assets/chars/zombie/poses/zombie_hold1.png';

  static const String assets_chars_zombie_poses_zombie_hold2_png = 'assets/chars/zombie/poses/zombie_hold2.png';
  static const String wombie$assets_chars_zombie_poses_zombie_hold2_png = 'packages/wombie/assets/chars/zombie/poses/zombie_hold2.png';

  static const String assets_chars_zombie_poses_zombie_hurt_png = 'assets/chars/zombie/poses/zombie_hurt.png';
  static const String wombie$assets_chars_zombie_poses_zombie_hurt_png = 'packages/wombie/assets/chars/zombie/poses/zombie_hurt.png';

  static const String assets_tiles_tile_0001_png = 'assets/tiles/tile_0001.png';
  static const String wombie$assets_tiles_tile_0001_png = 'packages/wombie/assets/tiles/tile_0001.png';
}
